from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/AToL-Bioinformatics/genome-launcher-workflow as a module
module genome_launcher_workflow:
    snakefile: 
        github("AToL-Bioinformatics/genome-launcher-workflow", path="workflow/Snakefile", tag="0.16.0")
    config:
        config


# use all rules from https://github.com/AToL-Bioinformatics/genome-launcher-workflow
use rule * from genome_launcher_workflow
