containers:
  agp_tpf_utils: "docker://ghcr.io/sanger-tol/agp-tpf-utils:1.3.4"
  atol_genome_launcher: "docker://quay.io/biocontainers/atol-genome-launcher:0.19.1--pyhdfd78af_0"
  atol_qc_raw_ont: "docker://quay.io/biocontainers/atol-qc-raw-ont:0.2.1--pyhdfd78af_0"
  atol_qc_raw_pacbio: "docker://quay.io/biocontainers/atol-qc-raw-pacbio:0.2.2--pyhdfd78af_0"
  atol_qc_raw_shortread: "docker://quay.io/biocontainers/atol-qc-raw-shortread:0.3.1--pyhdfd78af_0"
  bbmap: "docker://quay.io/biocontainers/bbmap:39.81--h9b5c0a0_1"
  curl: "docker://quay.io/curl/curl:8.20.0"
  ena_webin_cli: "docker://quay.io/biocontainers/ena-webin-cli:9.0.3--hdfd78af_0"
  pigz: "docker://quay.io/biocontainers/pigz:2.8"
  rclone: "docker://rclone/rclone:sha-e9fddaa"
  seqkit: "docker://quay.io/biocontainers/seqkit:2.13.0--he881be0_0"
  wget: "docker://quay.io/biocontainers/wget:1.25.0"
manifest: "config/manifest.json"
webin_ftp: "ftp://webin2.ebi.ac.uk/"
