
- id: xcParTurq1.1.pacbio_hifi.phased
  assembler: "hifiasm"
  long_read_dataset: xcParTurq1
  long_read_platform: pacbio_hifi
  hic_dataset: xcParTurq1
  phased_assembly: true
  purge: false
  busco_lineage: mollusca_odb12
  find_mito: true
  find_plastid: false
  mitohifi_mito_genetic_code: 5
  mitohifi_reference_species: "Octopus vulgaris"
- id: xcParTurq1.1.oatk
  assembler: "oatk"
  long_read_dataset: xcParTurq1
  long_read_platform: pacbio_hifi
  busco_lineage: mollusca_odb12
  oatk_mito_hmm: https://github.com/c-zhou/OatkDB/raw/main/v20230921/mollusca_mito.fam
- id: xcParTurq1.1.mitohifi
  assembler: "mitohifi"
  long_read_dataset: xcParTurq1
  long_read_platform: pacbio_hifi
  busco_lineage: mollusca_odb12
  mitohifi_mito_genetic_code: 5
  mitohifi_reference_species: "Octopus vulgaris"